---
version: '2'
services:
  postgress:
    hostname: postgress
    container_name: postgress
    image: postgres:13.4-alpine3.14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5433'